Bugfix/e UI 2925 activity tracker proxy 3 ud (#1062)
* refactored the api to take more advantage of tcp proxy tunnel

* fixed open/closed routes

* fixing functional test issues

* fixed work allocation route

* fixed work allocation tests

* Revert "fixed work allocation route"

This reverts commit b3b76e51

* ccd activity tracker

* ccd activity tracker

* lint error fix

* Bumping chart version

* nodeMock updated for activity tracker api.

* update search case mock data in nodeMock

* test update validation count of expected cases

* init commit

* Adding logging to the activity tracker

* add safety check whilst accessing user info object

* fix ng lint errors

* Update the activity_next_poll_request_ms to 30 seconds and activity_retry to 30.

* remove proxy.end() inside of activityTracker

* EUI-2925 rebase fallout

* EUI-2925 further rebase fallout

* EUI-3638 new version of toolkit

* Bumping chart version

* Bumping chart version

* EUI-2925 new toolkit version

* Revert "Merge branch 'master' into bugfix/EUI-2925-activity-tracker-proxy-3"

This reverts commit 04643fa3960c78b02e9b55a6fb90bda9711f0961.

* EUI-2925 new version

* EUI-2925 new version with 10 second post

* functional test fix to handle debounce on show hide eval delay.

* Bumping chart version

* updating https middleware proxy in mc webapp

* Update Chart.yaml

* Update Chart.yaml

* Update values.yaml

* Update values.yaml

* Update package.json

* added CVe's fix

* updated lock file

* Update package.json

Going back to an earlier version of @types/node as a result of getting this error both locally and on Jenkins:

ERROR in node_modules/@types/node/globals.global.d.ts(1,44): error TS2304: Cannot find name 'globalThis'.

* Bumping chart version

* Update index.ts

`EnhancedRequest.session` apparently cannot be optional.

TS2345: Argument of type 'EnhancedRequest' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.

* Update index.ts

`sucessCallback` in `auth` needs to have an `EnhancedRequest` as `passport` isn't automatically a property of `session`.

Addresses this:
TS2339: Property 'passport' does not exist on type 'Session & Partial<SessionData>'.

* http-proxy-middleware version issue

Version 1.2.0 introduced a type that causes a compilation error. That's present in all subsequent versions. The last version that actually compiles is 1.1.2, hence this change.

* Resolve xmlhttprequest-ssl to version 1.6.2

Just to see...

* Nope

Still complaining about the redis issue, even though it's marked as a low priority. Will leave it for others to fix...

* EUI-2925 yarn audit stuff

* fix values.yaml

* EUI-2925 yarn audit

* using SERVICES_CCD_COMPONENT_API_PATH instead of SERVICES_CCD_ACTIVITY_API_PATH

* lint fix

* fixed protractor issue by cleaning up unwanted lib changes in yarn.lock. updated yarn.lock with master copy and current package.json changes on top of it

* Feature/activity tracker ud (#1061)

* activity tracker changes

* lint error fix

* audit issues

* fix the failing unit tests

* tests updated inline with api response change.

* functional test fix to land in correct tab for validation

(cherry picked from commit 277483d55e60b0124173d0d0969ab987e7fd09cc)

* test fix to handle empty column header labels in case list

Co-authored-by: Uday Denduluri <uday.denduluri@gmail.com>
Co-authored-by: sreekanthpuligadda <sreekanth.puligadda@hmcts.net>

* EUI-2925 toolkit version with 5 second posts

* EUI-2925 re-added activity-resolver

* EUI-2925 toolkit upgrade

Co-authored-by: Pardeep Singh Basi <paddybasi@gmail.com>
Co-authored-by: Uday Denduluri <uday.denduluri@gmail.com>
Co-authored-by: hmcts-jenkins-xui <61146108+hmcts-jenkins-xui[bot]@users.noreply.github.com>
Co-authored-by: sreekanthpuligadda <sreekanth.puligadda@hmcts.net>
Co-authored-by: kuda <ku-da@hotmail.co.uk>
Co-authored-by: Adnan Akgun <adnan.akgun@netclipper.co.uk>
Co-authored-by: Jenkins <nobody@nowhere>
Co-authored-by: Mo-Lala84 <49687052+Mo-Lala84@users.noreply.github.com>
Co-authored-by: Lee Pavlou <leepavlou@Lees-MacBook-Pro.local>
Co-authored-by: Paul Graham <paul.graham@hmcts.net>
Co-authored-by: ernestman28 <ernest_man28@hotmail.com>